name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

# Define permissions needed for creating releases
permissions:
  contents: write  # This is required for creating releases

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Extract version from release
        id: get_version
        shell: bash
        run: |
          # Extract version without the 'v' prefix (e.g., v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update version numbers
        run: python update_version.py ${{ steps.get_version.outputs.version }}

      - name: Build with PyInstaller
        run: |
          pyinstaller app.spec

      - name: Run Inno Setup
        uses: robin24/inno-setup-action@v1
        with:
          filepath: ./sim-cpdlc.iss

      - name: Upload Release Asset
        id: upload_release_asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installer/Sim-CPDLC-${{ steps.get_version.outputs.version }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
